#!/bin/bash
set -x

echo -n "deploy"

cd $OPENSHIFT_DATA_DIR/gradle-2.12/bin
rm -rf src
rm -rf build.gradle
rm -rf settings.gradle
cp -r $OPENSHIFT_REPO_DIR/src $OPENSHIFT_DATA_DIR/gradle-2.12/bin
cp $OPENSHIFT_REPO_DIR/settings.gradle $OPENSHIFT_DATA_DIR/gradle-2.12/bin
cp $OPENSHIFT_REPO_DIR/build.gradle $OPENSHIFT_DATA_DIR/gradle-2.12/bin
./gradle build -x test
echo -n "start"
cd $OPENSHIFT_DATA_DIR/gradle-2.12/bin/build/libs
#gradle build
cp *.jar $OPENSHIFT_DATA_DIR/jdk1.8.0_91/bin
cd $OPENSHIFT_DATA_DIR/jdk1.8.0_91/bin
./java -Xms384m -Xmx496m -jar *.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &