language: java
jdk:
- oraclejdk8
deploy:
  provider: openshift
  user: m.ostapowicz@stud.elka.pw.edu.pl
  password:
    secure: sLmAvmzVHeOXc/dPo9z9LQxu14UnPqzq+Qu3/mWjUQMhWUhqHC/DER6LAOPcr3L+R3GSr0NmCThYVn+jdXqSmpRngkG3kWlLHoOtrYpsAMMvlqJaPeAUrhSNlTMdFNZ7jy/sWxRw3CcN5ORfcNw9XeiGmS3NKDUiEXpOdnmn7L2UeYllBVlFaD2KjVLUKLwWYbQ2wqXppNoQ0hFHFodvcJkwXi8bweVuiP1AYq3mpgQpTvKgs5ojPeRCBKiS1h+TYQhqknLIntSwdeNbEaZWfU7ugijQ2Q03NTwgIPUcvwIBQuZs0XPjyhjfv26whS+mHAPpheggwJowuS9UDj2zl6T7w/AbCtXxYEQd3AqjfoR8l4khjR7BIrxEAbngDFg1q+ljLzPZIglWxc9bMu04tYRYbYjOvOwzXjZtazR/P+0ozGLDNllG4PSAKPNBERJhViHNwdRzadFFjkj7vlxpQfGHcZ37PMyFTBlWWROkXAn2XHKQLOzUHV0Pgz36bVDHNyZ59HXYCIK1opMae+AB/zWwh/VlpIv0Q2yQXIlW3LxBgwj47KiuSuL+ozkDuYENusQzW/1XXzJLKvkrjKk5RLB/fckyXdycxoQcLmBjUVhOIRXsTAUFxpXCBkkgbQUbdSG3gLt/wMrTjhOXK5F7e/2ZLlczLg5Y26iMCzCP78k=
  app: chipanddale
  domain: pwprojects
  on:
    repo: Galfaroth7/spring_fun
