DROP ALL OBJECTS;

CREATE TABLE CHEESES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);

INSERT INTO CHEESES(NAME) VALUES ('Edam');
INSERT INTO CHEESES(NAME) VALUES ('Gouda');
INSERT INTO CHEESES(NAME) VALUES ('Rydzki');